-- THIS EXECUTES WHEN THE DOCKER CONTAINER IS STARTED DO NOT MODIFY!!!
DROP DATABASE IF EXISTS kairos;
CREATE DATABASE kairos;
DROP USER IF EXISTS 'kairos'@'%';
CREATE USER 'kairos'@'%' IDENTIFIED BY 'kairos';
GRANT ALL PRIVILEGES ON *.* TO 'kairos'@'%';
FLUSH PRIVILEGES;